/**
 * React Router DOM Proxy
 * This file re-exports everything from react-router-dom.
 * vite.config.ts aliases "react-router-dom" -> this file
 * and "react-router-dom-original" -> the actual package.
 * We import from the actual package node_modules path directly.
 */
export {
  BrowserRouter,
  HashRouter,
  MemoryRouter,
  Router,
  Route,
  Routes,
  Link,
  NavLink,
  Navigate,
  Outlet,
  useNavigate,
  useLocation,
  useParams,
  useSearchParams,
  useMatch,
  useRoutes,
  useHref,
  useInRouterContext,
  useNavigationType,
  useOutlet,
  useOutletContext,
  useResolvedPath,
  createBrowserRouter,
  createHashRouter,
  createMemoryRouter,
  createPath,
  createRoutesFromElements,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  parsePath,
  redirect,
  renderMatches,
  resolvePath,
  RouterProvider,
  ScrollRestoration,
  Form,
  useActionData,
  useAsyncError,
  useAsyncValue,
  useFetcher,
  useFetchers,
  useFormAction,
  useLoaderData,
  useMatches,
  useNavigation,
  useRevalidator,
  useRouteError,
  useRouteLoaderData,
  useSubmit,
  Await,
  defer,
} from 'react-router-dom';
